CXXFLAGS    = -fcilkplus -std=c++11 -g -Wall -O3 -funroll-loops -mavx -mtune=native -flax-vector-conversions 

all: perm_descentes_algo mots_binaires perm_generation

perm_descentes_algo: perm_descentes_algo.cpp
mots_binaires: mots_binaires.cpp
perm_generation: perm_generation.cpp
