CXXFLAGS    = -fcilkplus -std=c++11 -g -Wall -O3 -funroll-loops -mavx -mtune=native -flax-vector-conversions

all: sort cycle democilk demovect

sort: sort.cpp
cycle: cycle.cpp
democilk: democilk.cpp
demovect: demovect.cpp
